spring:
  application:
    name: demo-zk-service


server:
  port: 8880


com:
  alipay:
    sofa:
      rpc:
        registry:
          address: zookeeper://192.168.1.21:2181,192.168.1.22:2181,192.168.1.23:2181
        dubbo:
          port: 12222
        bolt:
          port: 12222
logging:
  path: ./logs
